-- V3
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE CH_TB_MOTO ADD DATA_FABRICACAO DATE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE = -1430 THEN
         NULL;
      ELSE
         RAISE;
      END IF;
END;
/
