-- V4
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE CH_TB_PATIO ADD OBSERVACAO VARCHAR2(500)';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE = -1430 THEN
         NULL;
      ELSE
         RAISE;
      END IF;
END;
/
